backend:
  name: github
  repo: Romain-14/la-pizzetteria
  branch: main
  base_url: https://tortue-ninja.netlify.app
  auth_endpoint: auth
  auth_type: implicit

# local_backend: true

media_folder: "public/images/"
public_folder: "/images/"

collections:

  # 🔹 INFOS GÉNÉRALES (fichier unique)
  - name: "infos"
    label: "Informations générales"
    files:
      - file: "src/content/infos.json"
        name: "infos"
        label: "Informations générales"
        fields:
          - { label: "Titre", name: "title", widget: "string", default: "Gastro-Resto" }
          - { label: "Ville", name: "city", widget: "string", default: "Nantes" }
          - { label: "URL", name: "site_url", widget: "string", default: "https://astro-decap-template.netlify.app" }
          - { label: "Sous-titre", name: "subtitle", widget: "string", default: "Cuisine maison • Produits frais • Sur place & à emporter" }
          - { label: "Description", name: "description", widget: "markdown", default: "Pizzaïolo Edmondo, dit Eddy, a mis son talent au service de vos papilles pour créer « La Pizzetteria » à Aigrefeuille-sur-Maine (44140).Aujourd’hui il passe la main à son jeune « padawan » Guillaume qu’il a su formé et qui continuera à mettre en valeur les produits italien.Laissez vous tenter par nos pizzas et desserts faits maison dans la tradition transalpine, ainsi que par nos vins et bières importés directement d’Italie. Nous sommes très fiers de vous proposer vos pizzas italiennes préférées faites maison."
          }
          - { label: "Description Google", name: "google_description", widget: "markdown", default: "Pizzeria artisanale à Aigrefeuille-sur-Maine (44140) – pizzas maison, pasta box et spécialités italiennes à emporter. Commande rapide par téléphone."
          }
          - { label: "Image de couverture", name: "cover_image", widget: "image", required: false }

  # 🔹 PIZZAS
  - name: "pizzas"
    label: "Pizzas"
    folder: "src/content/pizzas"
    create: true
    media_folder: "/public/images/pizzas"
    public_folder: "/images/pizzas"
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    identifier_field: "name"
    summary: "{{name}} - {{price}}€"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - label: "Base"
        name: "base"
        widget: "select"
        multiple: false
        options:
          - { label: "Sauce tomate", value: "sauce-tomate" }
          - { label: "Mozzarella", value: "mozzarella" }
          - { label: "Sauce tomate & mozzarella", value: "sauce-tomate-mozzarella" }
        required: true
      - label: "Ingrédients"
        name: "ingredients"
        widget: "list"
        required: true
        field:
            label: "Ingrédient"
            name: "ingredient"
            widget: "select"
            multiple: true
            options:
              - "Anchois"
              - "Artichauts"
              - "Aubergines"
              - "Basilic"
              - "Burrata"
              - "Câpres"
              - "Champignons"
              - "Chèvre"
              - "Chorizo"
              - "Copeaux de Parmesan"
              - "Crème carbonara (guanciale + œuf + pecorino)"
              - "Crème ciboulette"
              - "Crème de pistache maison"
              - "Crème fraîche"
              - "Gorgonzola"
              - "Jambon blanc"
              - "Jambon cru"
              - "Jaune d'œuf"
              - "Lardons"
              - "Miel"
              - "Mozzarella billes"
              - "Noix"
              - "Oeuf"
              - "Oignons"
              - "Olives"
              - "Pancetta"
              - "Parmesan"
              - "Pecorino"
              - "Pesto maison"
              - "Pistaches"
              - "Poivrons"
              - "Pommes de terre"
              - "Réduction balsamique"
              - "Roquette"
              - "Salade mixte"
              - "Sauce bolognaise maison"
              - "Sauce persillade"
              - "Saumon"
              - "Scarmoza fumée"
              - "Spianata"
              - "Speck"
              - "Taleggio"
              - "Thon"
              - "Thym"
              - "Tomates cerise"
            required: true
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Prix (€)", name: "price", widget: "number", value_type: "float", step: 0.1 }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field:
          label: "Tag"
          name: "tag"
          widget: "select"
          required: false
          options: ["Végétarien", "Épicé","Poisson", "Viande", "Charcuterie" ]
      - {
        label: "Mise en avant",
        name: "highlight",
        widget: "boolean",
        default: false,
        hint: "Cochez pour mettre cette pizza en avant sur la page d'accueil"}

  # 🔹 SPÉCIALITÉS (antipasti, charcuterie, fromages, pâtes)
  - name: "specialties"
    label: "Spécialités"
    folder: "src/content/specialties"
    create: true
    media_folder: "/public/images/specialties"
    public_folder: "/images/specialties"
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    identifier_field: "name"
    summary: "{{name}} ({{fields.formats.length}} formats)"
    sortable_fields: ["name", "price"]
    fields:
        - { label: "Nom", name: "name", widget: "string" }
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Image", name: "image", widget: "image" }
        - { label: "Type", name: "type", widget: "select", options: ["Antipasti", "Pâtes"] }
        - label: "Formats"
          name: "formats"
          widget: "list"
          summary: "{{fields.label}} - {{fields.price}}€"
          fields:
            - label: "Nom du format"
              name: "label"
              widget: "select"
              options:
                  - "1 personne"
                  - "8 personnes"   
            - {
                label: "Prix (€)",
                name: "price",
                widget: "number",
                value_type: "float",
                min: 0,
                step: 0.1
              }
        - {
          label: "Favoris",
          name: "isFavorite",
          widget: "boolean",
          default: false,
          hint: "Cochez pour mettre cette spécialité en avant sur la page d'accueil"}  
  # 🔹 PLATTER (assiettes de charcuterie/fromage à partager)
  - name: "platters"
    label: "Plateaux"
    folder: "src/content/platters"
    create: true
    media_folder: "/public/images/platters"
    public_folder: "/images/platters"
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    identifier_field: "name" # 🔥 IMPORTANT
    summary: "{{name}}" # 🔥 IMPORTANT
    sortable_fields: ["name"]
    fields:
        - { label: "Nom du produit", name: "name", widget: "string" }
        - { label: "Image", name: "image", widget: "image" }
        - label: "Formats"
          name: "formats"
          widget: "list"
          summary: "{{fields.label}} - {{fields.price}}€"
          fields:
            - label: "Nom du format"
              name: "label"
              widget: "select"
              options:
                  - "2 personnes"
                  - "4 personnes"   
            - {
                label: "Prix (€)",
                name: "price",
                widget: "number",
                value_type: "float",
                min: 0,
                step: 0.1
              }
        - label: "Ingrédients"
          name: "ingredients"
          widget: "list"
          field:
              label: "Ingrédient"
              name: "ingredient"
              widget: "select"
              multiple: true
              options:
                - "Beurre"
                - "Chèvre"
                - "Gorgonzola"
                - "Jambon"
                - "Jambon cru"
                - "Mozzarella"
                - "Olives"
                - "Pancetta"
                - "Parmesan"
                - "Roquette"
                - "Scamorza"
                - "Spianata"
                - "Speck"
                - "Taleggio"
                - "Tomates cerises"
        - {label: "Favoris",
          name: "isFavorite",
          widget: "boolean",
          default: false,
          hint: "Cochez pour mettre ce plateau en avant sur la page d'accueil"}
  # 🔹 DESSERTS
  - name: "desserts"
    label: "Desserts"
    folder: "src/content/desserts"
    media_folder: "/public/images/desserts"
    public_folder: "/images/desserts"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    identifier_field: "name"
    summary: "{{name}} - {{price}}€"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Prix (€)", name: "price", widget: "number", value_type: "float", step: 0.1 }
      - {
        label: "Favoris",
        name: "isFavorite",
        widget: "boolean",
        default: false,
        hint: "Cochez pour mettre ce dessert en avant sur la page d'accueil"}
  # 🔹 BOISSONS
  - name: "drinks"
    label: "Boissons"
    folder: "src/content/drinks"
    media_folder: "/public/images/drinks"
    public_folder: "/images/drinks"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    identifier_field: "name"
    summary: "{{name}} - {{price}}€"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - label: "Catégorie"
        name: "category"
        widget: "select"
        options: ["Digestif", "Vin", "Bière", "Soda", "Eau"]

      - { label: "Prix (€)", name: "price", widget: "number", value_type: "float", step: 0.1 }

      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field:
          label: "Tag"
          name: "tag"
          widget: "select"
          options: ["Avec alcool", "Sans alcool"]
      - {
        label: "Favoris",
        name: "isFavorite",
        widget: "boolean",
        default: false,
        hint: "Cochez pour mettre cette boisson en avant sur la page d'accueil"}
  # AVIS GOOGLE
  - name: "reviews"
    label: "Avis clients"
    folder: "src/content/reviews"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    identifier_field: "author"
    summary: "{{author}} - {{rating}} étoiles"
    fields:
      - { label: "Nom du client", name: "author", widget: "string" }      
      - { label: "Note", name: "rating", widget: "number", value_type: "int", min: 1, max: 5 }
      
      - { label: "Contenu de l'avis", name: "content", widget: "markdown" }
      
      - { label: "Date", name: "date", widget: "datetime", time_format: false }
      
      - { label: "Source", name: "source", widget: "select", options: ["Google", "Facebook", "Autre"], default: "Google" }
      
      - { label: "Mettre en avant", name: "featured", widget: "boolean", default: false }

  # 🔹 HORAIRES
  - name: "hours"
    label: "Horaires"
    files:
      - file: "src/content/hours/hours.json"
        name: "hours"
        label: "Horaires"
        widget: "object"
        fields:
          - label: "Lundi"
            name: "lundi"
            widget: "object"
            collapsed: true
            fields: &day_fields
              - { label: "Fermé", name: "closed", widget: "boolean", default: false }

              - label: "Plages horaires"
                name: "slots"
                widget: "list"
                max: 2
                collapsed: true
                fields:
                  - label: "Ouverture"
                    name: "open"
                    widget: "object"
                    fields:
                      - { label: "Heure", name: "hour", widget: "select", options: ["00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23"] }
                      - { label: "Minute", name: "minute", widget: "select", options: ["00","15","30","45"] }

                  - label: "Fermeture"
                    name: "close"
                    widget: "object"
                    fields:
                      - { label: "Heure", name: "hour", widget: "select", options: ["00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23"] }
                      - { label: "Minute", name: "minute", widget: "select", options: ["00","15","30","45"] }

          - { label: "Mardi", name: "mardi", widget: "object", collapsed: true, fields: *day_fields }
          - { label: "Mercredi", name: "mercredi", widget: "object", collapsed: true, fields: *day_fields }
          - { label: "Jeudi", name: "jeudi", widget: "object", collapsed: true, fields: *day_fields }
          - { label: "Vendredi", name: "vendredi", widget: "object", collapsed: true, fields: *day_fields }
          - { label: "Samedi", name: "samedi", widget: "object", collapsed: true, fields: *day_fields }
          - { label: "Dimanche", name: "dimanche", widget: "object", collapsed: true, fields: *day_fields }
  
  - name: "special"
    label: "Information spéciale"
    files:
      - file: "src/content/information/special.json"
        create: true
        name: "special"
        label: "Information spéciale"
        widget: "object"
        fields:
          - label: "Activer le message d'avertissement"
            name: "enabled"
            widget: "boolean"
            default: false
            required: false
          - label: "Contenu du message"
            name: "content"
            widget: "string"
